
# This workflow automatically publishes the HAF and TFA binaries for a given
# release.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: Build components

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: BIOS Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          
      - name: Run make in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@donotreply.com"
            make
