name: Build and Push Devcontiner Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: odp-platform-qemu-sbsa-devcontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "false"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short commit hash
        id: git_meta
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          platform: linux/amd64,linux/arm64
          imageName: ${{ env.REGISTRY }}/${{ github.repository }}
          cacheFrom: ${{ env.REGISTRY }}/${{ github.repository }}
          imageTag: latest,${{ steps.git_meta.outputs.short_sha }}
          push: always
